# Site
title: e-Rotaract.com
description: Together we can make our world a better place, join us!

logoo:
  url: logo/rotaract.svg
  position: center
  width: 300px
favicon:
  png: logo/rotaract-pink.png
  ico: logo/rotaract-pink.ico

baseurl:
include: ["_pages", ".well-known"]
permalink: /page/:title/
future: false

statistics: '<script src="https://cdn.counter.dev/script.js" data-id="76980790-dbae-4d03-bd6b-9e45bc645799" data-utcoffset="0"></script>'

links-side:
  - name: Masto
    icon: fab fa-mastodon
    url: /masto
    newtab: true
  - name: Insta
    icon: fab fa-instagram
    url: /instagram
    newtab: true
  - name: Videocall
    icon: fas fa-video
    url: /videocall
    newtab: true
  - name: Calendar
    icon: fas fa-calendar-alt
    url: /calendar
    newtab: true
  - name: Brand kit
    icon: fas fa-briefcase
    url: /brand-kit
    newtab: false
  - name: Feedback
    icon: fas fa-feather-alt
    url: /feedback
    newtab: true


verification: "<a rel='me' href='https://masto.ai/@rotaract'></a>"

# Authors
authors:
  eclub:
    name: e-Rotaract Beyond Frontiers
    description: International e-Rotaract created on 2021-10-10
    avatar: avatars/eclub.png
    email: hi@e-rotaract.com
    web: https://e-rotaract.com
    instagram: https://e-rotaract.com/instagram
    youtube:  https://e-rotaract.com/youtube
    facebook: https://e-rotaract.com/facebook
    linkedin: https://e-rotaract.com/linkedin
    twitter: https://e-rotaract.com/twitter
  iaco:
    name: IACO VIVACI
    description: Iaco Vivaci
    avatar: avatars/iaco.jpg
    email: hi@iaco.io
    web: https://iaco.io
    instagram: https://iaco.me/instagram
    youtube: https://iaco.me/youtube
    facebook: https://iaco.me/facebook
    linkedin: https://iaco.me/linkedin
    twitter: https://iaco.me/twitter

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-liquify
  - jekyll-target-blank
  - jekyll-redirect-from

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /post/page/:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Lazy Images
lazyimages: disabled

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
